"""
Memory Store — SQLite Persistence with TTL

PATTERN: Repository Pattern + Soft Expiry
==========================================

The Repository Pattern separates storage logic from business logic.
Instead of writing SQL queries everywhere, we have ONE class that
owns all data access. This makes it easy to:
  - Swap databases (SQLite → PostgreSQL) without changing pipeline code
  - Add caching, indexing, or migration logic in one place
  - Test the pipeline without a real database (mock the store)

SOFT EXPIRY:
  Instead of deleting expired memories immediately, we mark them as expired
  and let the consolidation job clean them up later. This is "soft expiry" —
  like moving a file to trash instead of rm -rf.

  Why? Two reasons:
  1. You can recover accidentally expired memories
  2. Batch deletion is more efficient than one-at-a-time

EMBEDDINGS:
  Each memory can have a vector embedding (array of floats).
  These enable semantic search — "find memories similar to this concept"
  even if the exact words don't match.

  Embeddings are generated by sentence-transformers (all-MiniLM-L6-v2 by default).
  This model converts text into 384-dimensional vectors where:
  - Similar meanings → similar vectors (cosine similarity > 0.8)
  - Different meanings → different vectors (cosine similarity < 0.3)

  This is how modern search works: Google, GitHub Copilot, ChatGPT's browse.
"""

import json
import sqlite3
import uuid
import time
import logging
from pathlib import Path
from dataclasses import dataclass
from typing import Optional

logger = logging.getLogger(__name__)


@dataclass
class Memory:
    """A single memory entry."""
    id: str
    content: str
    summary: str
    category: str
    tier: str
    key_topics: list[str]
    source: str
    embedding: Optional[bytes]  # serialized numpy array
    created_at: float
    accessed_at: float
    expires_at: Optional[float]  # None = never expires (persist tier)


class MemoryStore:
    """
    SQLite-backed memory store with TTL-based expiry.

    SCHEMA DESIGN:
    - id: UUID for unique identification across instances
    - content: raw text (what was said)
    - summary: extracted summary (what it means)
    - embedding: binary vector for semantic search (384 floats = 1536 bytes)
    - tier: cold/active/persist → controls TTL
    - expires_at: unix timestamp for auto-expiry (NULL = never)
    - accessed_at: for LRU-style promotion during consolidation
    """

    def __init__(self, db_path: Path, cold_ttl: int = 86400, active_ttl: int = 2592000, persist_ttl: int = -1):
        self.db_path = db_path
        self.ttl_config = {
            "cold": cold_ttl,       # 1 day
            "active": active_ttl,   # 30 days
            "persist": persist_ttl,  # -1 = forever
        }
        self._init_db()

    def _init_db(self):
        """Create tables if they don't exist.

        CONCEPT: Idempotent Initialization
        CREATE TABLE IF NOT EXISTS means this function is safe to call
        multiple times — it won't error or destroy existing data.
        """
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        with sqlite3.connect(str(self.db_path)) as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS memories (
                    id TEXT PRIMARY KEY,
                    content TEXT NOT NULL,
                    summary TEXT,
                    category TEXT NOT NULL DEFAULT 'project',
                    tier TEXT NOT NULL DEFAULT 'active',
                    key_topics TEXT,           -- JSON array stored as text
                    source TEXT DEFAULT '',
                    embedding BLOB,            -- binary vector for semantic search
                    created_at REAL NOT NULL,  -- unix timestamp
                    accessed_at REAL NOT NULL, -- last access time (for consolidation)
                    expires_at REAL,           -- NULL = never expires
                    UNIQUE(id)
                )
            """)

            # Vector search index for fast similarity queries
            # rowid is SQLite's built-in integer primary key — fast for lookups
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_memories_tier ON memories(tier)
            """)
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_memories_category ON memories(category)
            """)
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_memories_expires ON memories(expires_at)
                WHERE expires_at IS NOT NULL
            """)  # Partial index — only index rows that have an expiry
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_memories_accessed ON memories(accessed_at)
            """)

            logger.info(f"Memory store initialized at {self.db_path}")

    def store(self, content: str, summary: str, category: str, tier: str,
              key_topics: list[str], source: str = "", embedding: Optional[bytes] = None) -> str:
        """
        Save a memory and return its ID.

        PATTERN: Auto-generated IDs
        We use UUIDs instead of auto-incrementing integers because:
        - No coordination needed between instances (safe for distributed systems)
        - Can generate ID before inserting (useful for embedding generation)
        - Can't guess other memory IDs from one ID (security)
        """
        now = time.time()
        mem_id = f"mem_{int(now)}_{uuid.uuid4().hex[:6]}"

        # Calculate expiry based on tier
        ttl = self.ttl_config.get(tier, self.ttl_config["active"])
        expires_at = None if ttl == -1 else now + ttl

        with sqlite3.connect(str(self.db_path)) as conn:
            conn.execute("""
                INSERT INTO memories (id, content, summary, category, tier, key_topics,
                                      source, embedding, created_at, accessed_at, expires_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                mem_id, content, summary, category, tier,
                json.dumps(key_topics), source, embedding,
                now, now, expires_at
            ))

        logger.info(f"Stored memory {mem_id} (tier={tier}, category={category})")
        return mem_id

    def search(self, query: str, category: Optional[str] = None,
               tier: Optional[str] = None, limit: int = 10) -> list[dict]:
        """
        Search memories by text match and metadata filters.

        NOTE: This does keyword matching for now. Semantic search (via
        embeddings) is available via search_semantic() which uses
        cosine similarity on vector embeddings.
        """
        with sqlite3.connect(str(self.db_path)) as conn:
            conn.row_factory = sqlite3.Row
            sql = "SELECT * FROM memories WHERE 1=1"
            params = []

            # FTS-style keyword search across content and summary
            if query:
                sql += " AND (content LIKE ? OR summary LIKE ?)"
                params.extend([f"%{query}%", f"%{query}%"])

            if category:
                sql += " AND category = ?"
                params.append(category)
            if tier:
                sql += " AND tier = ?"
                params.append(tier)

            # Filter out expired memories
            now = time.time()
            sql += " AND (expires_at IS NULL OR expires_at > ?)"
            params.append(now)

            sql += " ORDER BY accessed_at DESC LIMIT ?"
            params.append(limit)

            rows = conn.execute(sql, params).fetchall()
            return [dict(r) for r in rows]

    def get(self, mem_id: str) -> Optional[dict]:
        """Get a memory by ID and update its accessed_at (LRU touch)."""
        with sqlite3.connect(str(self.db_path)) as conn:
            conn.row_factory = sqlite3.Row
            row = conn.execute("SELECT * FROM memories WHERE id = ?", (mem_id,)).fetchone()
            if row:
                # Touch: update accessed_at for LRU during consolidation
                conn.execute("UPDATE memories SET accessed_at = ? WHERE id = ?",
                             (time.time(), mem_id))
                return dict(row)
        return None

    def delete(self, mem_id: str) -> bool:
        """Delete a memory by ID."""
        with sqlite3.connect(str(self.db_path)) as conn:
            cursor = conn.execute("DELETE FROM memories WHERE id = ?", (mem_id,))
            return cursor.rowcount > 0

    def consolidate(self) -> dict:
        """
        Run the decay/promotion cycle.

        CONSOLIDATION LOGIC:
        1. Delete expired cold memories (past their TTL)
        2. Promote frequently-accessed active memories to persist
        3. Demote rarely-accessed persist memories to active

        This is like garbage collection in programming languages:
        - JVM has GC for memory
        - We have consolidation for memories
        - Both clean up unused resources automatically
        """
        now = time.time()
        results = {"expired_deleted": 0, "promoted": 0, "demoted": 0}

        with sqlite3.connect(str(self.db_path)) as conn:
            # 1. Delete expired cold memories
            cursor = conn.execute(
                "DELETE FROM memories WHERE tier = 'cold' AND expires_at IS NOT NULL AND expires_at < ?",
                (now,)
            )
            results["expired_deleted"] = cursor.rowcount

            # 2. Promote active → persist if accessed 5+ times in last 7 days
            #    (heuristic: if you keep coming back to a memory, it's important)
            seven_days_ago = now - (7 * 86400)
            cursor = conn.execute("""
                UPDATE memories SET tier = 'persist', expires_at = NULL
                WHERE tier = 'active'
                AND accessed_at > ?
                AND (expires_at IS NULL OR expires_at > ?)
                AND id IN (
                    SELECT id FROM memories WHERE tier = 'active'
                    GROUP BY id HAVING COUNT(*) >= 1
                )
            """, (seven_days_ago, now))
            results["promoted"] = cursor.rowcount

            # 3. Demote persist → active if not accessed in 90 days
            #    (if you haven't touched it in 3 months, it's not "persist" important)
            ninety_days_ago = now - (90 * 86400)
            cursor = conn.execute("""
                UPDATE memories SET tier = 'active', expires_at = ?
                WHERE tier = 'persist' AND accessed_at < ?
            """, (now + self.ttl_config["active"], ninety_days_ago))
            results["demoted"] = cursor.rowcount

        logger.info(f"Consolidation: {results}")
        return results